from setuptools import setup

package_name = "omninav_step_scheduler"

setup(
    name=package_name,
    version="0.1.0",
    packages=[package_name],
    data_files=[
        ("share/ament_index/resource_index/packages", [f"resource/{package_name}"]),
        (f"share/{package_name}", ["package.xml", "HANDOFF.md"]),
        (f"share/{package_name}/launch", [
            "launch/scheduler_dryrun.launch.py",
            "launch/scheduler_isaac.launch.py",
            "launch/scheduler_real_models_isaac.launch.py",
            "launch/scheduler_real_guarded.launch.py",
            "launch/internnav_go2_direct.launch.py",
        ]),
        (f"share/{package_name}/config", [
            "config/scheduler_default.yaml",
            "config/scheduler_safe.yaml",
            "config/scheduler_fast.yaml",
            "config/scheduler_isaac_real_models.yaml",
            "config/scheduler_isaac_development.yaml",
            "config/scheduler_isaac_v14_multimodal.yaml",
            "config/scheduler_isaac_sim2real.yaml",
            "config/internnav_go2_direct.yaml",
        ]),
        (f"share/{package_name}/scripts", [
            "scripts/smoke_test_scheduler.py",
            "scripts/publish_test_instruction.py",
            "scripts/replay_episode.py",
            "scripts/run_internnav_go2_direct_epyc.sh",
        ]),
    ],
    install_requires=["setuptools"],
    zip_safe=True,
    maintainer="railgun",
    maintainer_email="railgun@example.com",
    description="OmniNav fast layer plus Step semantic supervisor scheduler.",
    license="MIT",
    tests_require=["pytest"],
    entry_points={
        "console_scripts": [
            "mission_manager_node = omninav_step_scheduler.mission_manager_node:main",
            "omninav_scheduler_node = omninav_step_scheduler.omninav_scheduler_node:main",
            "omninav_model_client_node = omninav_step_scheduler.omninav_model_client_node:main",
            "omninav_remote_model_client_node = omninav_step_scheduler.omninav_remote_model_client_node:main",
            "internnav_go2_client_node = omninav_step_scheduler.internnav_go2_client_node:main",
            "internnav_scheduler_node = omninav_step_scheduler.internnav_scheduler_node:main",
            "step_supervisor_node = omninav_step_scheduler.step_supervisor_node:main",
            "step_http_client_node = omninav_step_scheduler.step_http_client_node:main",
            "step_role_router_node = omninav_step_scheduler.step_role_router_node:main",
            "route_choice_verifier_node = omninav_step_scheduler.route_choice_verifier_node:main",
            "semantic_stop_verifier_node = omninav_step_scheduler.semantic_stop_verifier_node:main",
            "visible_to_stop_monitor_node = omninav_step_scheduler.visible_to_stop_monitor_node:main",
            "route_stop_primitive_bridge_node = omninav_step_scheduler.route_stop_primitive_bridge_node:main",
            "step_pending_policy_node = omninav_step_scheduler.step_pending_policy_node:main",
            "primitive_executor_node = omninav_step_scheduler.primitive_executor_node:main",
            "safe_cmd_mux_node = omninav_step_scheduler.safe_cmd_mux_node:main",
            "sensor_only_planner_node = omninav_step_scheduler.sensor_only_planner_node:main",
            "semantic_executive_node = omninav_step_scheduler.semantic_executive_node:main",
            "semantic_recovery_bridge_node = omninav_step_scheduler.semantic_recovery_bridge_node:main",
            "metrics_logger_node = omninav_step_scheduler.metrics_logger_node:main",
            "mock_step_client_node = omninav_step_scheduler.mock_clients:main_step",
            "mock_omninav_client_node = omninav_step_scheduler.mock_clients:main_omninav",
            "mock_safety_status_node = omninav_step_scheduler.mock_clients:main_safety",
        ],
    },
)
