#!/usr/bin/env python3
"""Mechanically derive the four frozen T4.2-R3 sensor configurations."""

from __future__ import annotations

import argparse
from pathlib import Path


def replace_once(text: str, old: str, new: str) -> str:
    count = text.count(old)
    if count != 1:
        raise RuntimeError(f"expected one config token, found {count}: {old!r}")
    return text.replace(old, new)


def nvblox_variant(base: str, *, depth: bool, lidar: bool) -> str:
    text = replace_once(base, "    num_cameras: 1", f"    num_cameras: {1 if depth else 0}")
    text = replace_once(
        text,
        "    integrate_lidar_rate_hz: 0.0",
        f"    integrate_lidar_rate_hz: {10.0 if lidar else 0.0}",
    )
    text = replace_once(text, "    use_depth: true", f"    use_depth: {str(depth).lower()}")
    text = replace_once(
        text,
        "    use_lidar: false",
        f"    use_lidar: {str(lidar).lower()}\n"
        "    lidar_width: 180\n"
        "    lidar_height: 8\n"
        "    lidar_min_valid_range_m: 0.10\n"
        "    use_non_equal_vertical_fov_lidar_params: true\n"
        "    min_angle_below_zero_elevation_rad: 0.2617993878\n"
        "    max_angle_above_zero_elevation_rad: 0.3490658504\n"
        "    use_lidar_motion_compensation: false\n"
        "    pointcloud2_timestamps_are_relative: false",
    )
    return replace_once(text, "    input_qos: DEFAULT", "    input_qos: SENSOR_DATA")


def nav2_variant(
    base: str, *, depth: bool, lidar: bool, clearing: bool
) -> str:
    plugins = "      plugins: [nvblox_layer, inflation_layer]"
    if base.count(plugins) != 2:
        raise RuntimeError("expected local and global Nvblox plugin lists")
    replacement = (
        "      plugins: [nvblox_layer, footprint_clearing_layer, inflation_layer]"
        if clearing
        else plugins
    )
    text = base.replace(plugins, replacement)
    if clearing:
        plugin = (
            "      footprint_clearing_layer:\n"
            "        plugin: nav2_footprint_clearing_layer::FootprintClearingLayer\n"
            "        enabled: true\n"
            f"        require_depth: {str(depth).lower()}\n"
            f"        require_lidar: {str(lidar).lower()}\n"
            "        footprint_radius_m: 0.32\n"
            "        startup_edge_m: 0.0\n"
            "        obstacle_min_height_m: 0.05\n"
            "        obstacle_max_height_m: 1.5\n"
            "        data_timeout_sec: 0.35\n"
            "        tf_timeout_sec: 0.20\n"
        )
        marker = "      inflation_layer:\n"
        if text.count(marker) != 2:
            raise RuntimeError("expected local and global inflation layers")
        text = text.replace(marker, plugin + marker)
    text = replace_once(text, "      topic: /go2/depth/points", "      topic: /go2/safety/points")
    header = (
        "# Generated by scripts/build_t4_2_r3_configs.py.\n"
        f"# geometry_sources: d435i={str(depth).lower()}, lidar={str(lidar).lower()}\n"
        f"# pose_verified_footprint_clearing: {str(clearing).lower()}\n"
        "# Safety invariants: robot_radius=0.30, padding=0.02, inflation=0.40.\n"
    )
    return header + text


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--config-dir", type=Path, default=Path("configs/internnav_t4"))
    args = parser.parse_args()
    root = args.config_dir.resolve()
    nvblox = (root / "nvblox_gt_pose.yaml").read_text(encoding="utf-8")
    nav2 = (root / "nav2_nvblox_gt_pose.yaml").read_text(encoding="utf-8")
    variants = {
        "d435i": (True, False, False),
        "lidar": (False, True, False),
        "fused": (True, True, False),
        "fused_clearing": (True, True, True),
        "fused_clearing_diag_timeout": (True, True, True),
    }
    for name, (depth, lidar, clearing) in variants.items():
        (root / f"t4_2_r3_{name}_nvblox.yaml").write_text(
            nvblox_variant(nvblox, depth=depth, lidar=lidar), encoding="utf-8"
        )
        nav2_text = nav2_variant(nav2, depth=depth, lidar=lidar, clearing=clearing)
        if name == "fused_clearing_diag_timeout":
            if nav2_text.count("        data_timeout_sec: 0.35") != 2:
                raise RuntimeError("expected local/global clearing freshness settings")
            nav2_text = nav2_text.replace(
                "        data_timeout_sec: 0.35",
                "        data_timeout_sec: 2.50",
            )
            nav2_text = (
                "# Isaac diagnostic only: 2.50 s exceeds the measured 2.211 s max frame gap.\n"
                "# Real Go2 must use the 0.35 s default or a measured hardware bound.\n"
                + nav2_text
            )
        (root / f"t4_2_r3_{name}.yaml").write_text(nav2_text, encoding="utf-8")


if __name__ == "__main__":
    main()
