#!/usr/bin/env bash
set -eo pipefail

ATTEMPT="${1:?attempt}"
HORIZON_M="${2:?horizon_m: 0.5/0.75/1.0/1.5}"
REFRESH_DISTANCE_M="${3:?refresh_distance_m: 0.2/0.3/0.4}"
REFRESH_TIME_SEC="${4:?refresh_time_sec: 1/2/3}"
VALIDITY_SEC="${5:-5.0}"
DEVIATION_M="${6:-0.60}"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LABEL_H="${HORIZON_M//./p}"
LABEL_D="${REFRESH_DISTANCE_M//./p}"
LABEL_T="${REFRESH_TIME_SEC//./p}"
export INTERNVLA_T4_RUN_LABEL="t4_5_h${LABEL_H}_d${LABEL_D}_t${LABEL_T}"
export INTERNVLA_T4_ENABLE_RECOVERY=1
export INTERNVLA_T4_ENFORCE_RECOVERY_GATE="${INTERNVLA_T4_ENFORCE_RECOVERY_GATE:-0}"
export INTERNVLA_T4_MIN_SR_OVERRIDE="${INTERNVLA_T4_MIN_SR_OVERRIDE:-0.0}"
export INTERNVLA_T3_NAVIGATE_GOAL_MAX_DISTANCE_M="$HORIZON_M"
export INTERNVLA_T4_REFRESH_DISTANCE_M="$REFRESH_DISTANCE_M"
export INTERNVLA_T4_REFRESH_TIME_SEC="$REFRESH_TIME_SEC"
export INTERNVLA_T4_TRAJECTORY_VALIDITY_SEC="$VALIDITY_SEC"
export INTERNVLA_T4_TRAJECTORY_DEVIATION_M="$DEVIATION_M"
exec bash "$ROOT/run_t4_sensor_gate.sh" t4_4 model "$ATTEMPT"
